name: xoleric_music
description: XOLERIC - Professional Music Player & Download Manager
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Audio
  just_audio: ^0.9.46
  on_audio_query: ^2.9.0
  audio_service: ^0.18.17

  # State
  provider: ^6.1.5

  # Navigation
  go_router: ^17.5.0

  # Storage
  shared_preferences: ^2.5.5

  # Download
  dio: ^5.7.0
  path_provider: ^2.1.6

  # Permission
  permission_handler: ^11.4.0

  # UI
  dynamic_color: ^1.7.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0

  # Utils
  intl: ^0.20.2
  collection: ^1.19.1
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
